// when user visits frontend → socket connection is created
// that socket.id is generated by backend and should be stored in User model

import User from "../models/user.model.js";

export const socketHandler = (io) => {
  // (socket) represents one connected user
  io.on("connection", (socket) => {
    console.log("User connected:", socket.id);

    // ============================================
    // FRONTEND → BACKEND IDENTIFICATION
    // ============================================
    // frontend sends: socket.emit("identity", { userId })
    // backend receives it here and stores socket.id in DB

    socket.on("identity", async ({ userId }) => {
      try {
        // update user with current socketId and mark online
        await User.findByIdAndUpdate(
          userId,
          {
            socketId: socket.id,
            isOnline: true,
          },
          { new: true },
        );

        // (optional debug)
        console.log(`User ${userId} mapped to socket ${socket.id}`);
      } catch (error) {
        console.log("Identity error:", error);
      }
    });

    // ============================================
    // DISCONNECT HANDLER
    // ============================================
    // when user closes tab / refreshes / loses connection

    socket.on("disconnect", async () => {
      try {
        // IMPORTANT:
        // here we DON'T have userId directly
        // so we find user by socketId

        await User.findOneAndUpdate(
          { socketId: socket.id }, // find user by socketId
          {
            socketId: null,
            isOnline: false,
          },
        );

        console.log(`Socket disconnected: ${socket.id}`);
      } catch (error) {
        console.log("Disconnect error:", error);
      }
    });
  });
};
